// Generated by CoffeeScript 1.7.1

/*
  Main game app
 */

(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  game.App = (function(_super) {
    __extends(App, _super);

    App.prototype.DT = "game.App";

    App.VID = "app-game";

    function App(el) {
      this.el = el;
      App.__super__.constructor.apply(this, arguments);
      console.log(this.DT, "Init.");
    }

    return App;

  })(abstract.Object);

}).call(this);
