// Generated by CoffeeScript 1.7.1

/*
  Level container
 */

(function() {
  dataTypes.Level = {
    get: function(geometry, actors) {
      return {
        geometry: geometry,
        actors: actors
      };
    }
  };

}).call(this);
