// Generated by CoffeeScript 1.7.1

/*
  This data type represent 2d matrix
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  dataTypes.Matrix2d = (function(_super) {
    __extends(Matrix2d, _super);

    Matrix2d.prototype.DT = "dataTypes.Matrix2d";

    function Matrix2d(data) {
      if (data == null) {
        data = {};
      }
      this.getFlatCellCoords = __bind(this.getFlatCellCoords, this);
      this.isCellContainsData = __bind(this.isCellContainsData, this);
      this.getData = __bind(this.getData, this);
      this.removeData = __bind(this.removeData, this);
      this.putData = __bind(this.putData, this);
      this.init = __bind(this.init, this);
      Matrix2d.__super__.constructor.apply(this, arguments);
      this.set("mdata", data);
    }

    Matrix2d.prototype.init = function() {
      Matrix2d.__super__.init.apply(this, arguments);
      return this.set("mdata", null);
    };

    Matrix2d.prototype.putData = function(cell, data) {
      return this.tobject.set("mdata", "" + cell[0] + "." + cell[1], data);
    };

    Matrix2d.prototype.removeData = function(cell) {
      return this.tobject.set("mdata", "" + cell[0] + "." + cell[1], void 0);
    };

    Matrix2d.prototype.getData = function(cell) {
      return this.tobject.get("mdata", "" + cell[0] + "." + cell[1]);
    };

    Matrix2d.prototype.isCellContainsData = function(cell) {
      return this.getData(cell) != null;
    };

    Matrix2d.prototype.getFlatCellCoords = function() {
      var cells, col, mdata, row, x, y;
      cells = [];
      mdata = this.get("mdata");
      for (x in mdata) {
        row = mdata[x];
        for (y in row) {
          col = row[y];
          cells.push([x, y]);
        }
      }
      return cells;
    };

    Matrix2d.createFromLevelObject = function(lobj) {
      return new dataTypes.Matrix2d(utils.serializers.Level.serializeObjectToWorldTree(lobj));
    };

    return Matrix2d;

  })(chms.ard.AbstractReactiveData);

}).call(this);
