// Generated by CoffeeScript 1.7.1

/*
  Entity entry for entities database
 */

(function() {
  dataTypes.AssetEntry = {
    get: (function(_this) {
      return function(id, name) {
        return {
          id: id,
          name: name
        };
      };
    })(this)
  };

}).call(this);
