// Generated by CoffeeScript 1.7.1

/*
  2d position
 */

(function() {
  dataTypes.Pos = {
    get: function(x, y) {
      return [x, y];
    },
    isEqual: function(cell1, cell2) {
      return cell1[0] === cell2[0] && cell1[1] === cell2[1];
    }
  };

}).call(this);
