// Generated by CoffeeScript 1.7.1

/*
  Global namespaces
 */

(function() {
  window.levelEditor = {
    view: {},
    data: {},
    modules: {},
    serializers: {},
    helpers: {}
  };

  window.gameLogic = {
    data: {},
    modules: {},
    entities: {},
    characters: {}
  };

  window.utils = {
    serializers: {},
    helpers: {}
  };

  window.dataTypes = {};

}).call(this);
