// Generated by CoffeeScript 1.7.1

/*
  Global namespaces
 */

(function() {
  window.levelEditor = {
    view: {},
    data: {},
    modules: {},
    serializers: {},
    helpers: {}
  };

  window.gameLogic = {
    data: {},
    modules: {},
    entities: {},
    actors: {}
  };

  window.gameSession = {};

  window.utils = {
    serializers: {},
    helpers: {},
    lib: {}
  };

  window.dataTypes = {};

  window.data = {};

  window.models = {
    actors: {}
  };

  window.abstract = {};

}).call(this);
