// Generated by CoffeeScript 1.7.1

/*
  Level serializer
 */

(function() {
  utils.serializers.Level = {
    serialize: function(level) {
      var cell, cells, cid, d, h, serialized, xcell, xcells, _i, _len;
      h = utils.helpers.Level;
      serialized = {};
      cells = level.get("levelCells");
      for (_i = 0, _len = cells.length; _i < _len; _i++) {
        cell = cells[_i];
        xcells = h.getCrossCellsForCell(cell);
        cid = h.getCellId(cell);
        serialized[cid] = {
          x: cell[0],
          y: cell[1]
        };
        for (d in xcells) {
          xcell = xcells[d];
          if (!level.isCellBelongs(xcell)) {
            serialized[cid][d] = {
              face: "black-wall",
              type: "wall"
            };
          }
        }
      }
      return serialized;
    },
    serializeToString: function(level) {
      return JSON.stringify(utils.serializers.Level.serialize(level));
    },
    parseSerialized: function(serialized) {
      var cell, cid, level;
      level = [];
      for (cid in serialized) {
        cell = serialized[cid];
        level.push([cell.x, cell.y]);
      }
      return level;
    },
    parseSerializedFromString: function(serialized) {
      serialized = JSON.parse(serialized);
      return utils.serializers.Level.parseSerialized(serialized);
    }
  };

}).call(this);
