// Generated by CoffeeScript 1.7.1

/*
  Actors on level
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  levelEditor.data.LevelActors = (function(_super) {
    __extends(LevelActors, _super);

    function LevelActors() {
      this.findActorIndexByPos = __bind(this.findActorIndexByPos, this);
      this.getActorOnCell = __bind(this.getActorOnCell, this);
      this.isAnyActorOnCell = __bind(this.isAnyActorOnCell, this);
      this.updateActor = __bind(this.updateActor, this);
      this.placeActor = __bind(this.placeActor, this);
      this.init = __bind(this.init, this);
      return LevelActors.__super__.constructor.apply(this, arguments);
    }

    LevelActors.prototype.DT = "levelEditor.data.LevelActors";

    LevelActors.prototype.init = function() {
      LevelActors.__super__.init.apply(this, arguments);
      return this.set("actors", []);
    };

    LevelActors.prototype.placeActor = function(actorpos) {
      if (!this.isAnyActorOnCell(actorpos.cell)) {
        return this.tarray.push("actors", actorpos);
      } else {
        return console.warn(this.DT, "placeActor: Actor already exists on " + actorpos.cell);
      }
    };

    LevelActors.prototype.updateActor = function(actorpos) {
      var i;
      if ((i = this.findActorIndexByPos(actorpos.cell)) > -1) {
        this.tarray["delete"]("actors", i);
        return this.placeActor(actorpos);
      } else {
        throw "" + this.DT + ": Actor not exist on a given cell " + actorpos.cell;
      }
    };

    LevelActors.prototype.isAnyActorOnCell = function(cell) {
      return this.getActorOnCell(cell) != null;
    };

    LevelActors.prototype.getActorOnCell = function(cell) {
      var i;
      if ((i = this.findActorIndexByPos(cell)) > -1) {
        return this.get("actors")[i];
      } else {
        return null;
      }
    };

    LevelActors.prototype.findActorIndexByPos = function(pos) {
      var res;
      res = this.get("actors").map(function(e, i) {
        return [e, i];
      }).filter(function(e) {
        return dataTypes.Pos.isEqual(e[0].cell, pos);
      });
      if (res.length === 1) {
        return res[0][1];
      } else if (res.length === 0) {
        return -1;
      } else {
        throw "" + this.DT + ": There are two or more actor on a given pos " + pos;
      }
    };

    return LevelActors;

  })(chms.ard.AbstractReactiveData);

}).call(this);
