// Generated by CoffeeScript 1.7.1

/*
  UI modes
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  levelEditor.data.UiModes = (function(_super) {
    __extends(UiModes, _super);

    UiModes.prototype.DT = "levelEditor.data.UiModes";

    UiModes.MODE_SELECT = "m_select";

    UiModes.MODE_NAVIGATE = "m_navigate";

    function UiModes() {
      this.init = __bind(this.init, this);
      UiModes.__super__.constructor.apply(this, arguments);
      console.log(this.DT, "Init.");
    }

    UiModes.prototype.init = function() {
      UiModes.__super__.init.apply(this, arguments);
      return this.set("currentMode", this.s.MODE_SELECT);
    };

    return UiModes;

  })(chms.ard.AbstractReactiveData);

}).call(this);
