// Generated by CoffeeScript 1.7.1

/*
  Various helpers for level data
 */

(function() {
  levelEditor.helpers.Level = {
    getCrossCellsForCell: function(cell) {
      var x, y;
      x = cell[0];
      y = cell[1];
      return {
        n: [x, y - 1],
        s: [x, y + 1],
        e: [x - 1, y],
        w: [x + 1, y]
      };
    },
    getCellId: function(cell) {
      return "" + cell[0] + "x" + cell[1];
    }
  };

}).call(this);
