// Generated by CoffeeScript 1.7.1

/*
  Editor hotkeys
 */

(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  levelEditor.modules.Hotkeys = (function(_super) {
    __extends(Hotkeys, _super);

    Hotkeys.prototype.DT = "levelEditor.modules.Hotkeys";

    function Hotkeys(app) {
      this.app = app;
      Hotkeys.__super__.constructor.apply(this, arguments);
      console.log(this.DT, "Init.");
      this.dUiModes = this.app.data.get("ui-modes");
      keyboardJS.bind('1', null, (function(_this) {
        return function(e) {
          return _this.dUiModes.set("currentMode", _this.dUiModes.s.MODE_SELECT);
        };
      })(this));
      keyboardJS.bind('2', null, (function(_this) {
        return function(e) {
          return _this.dUiModes.set("currentMode", _this.dUiModes.s.MODE_NAVIGATE);
        };
      })(this));
    }

    return Hotkeys;

  })(levelEditor.Object);

}).call(this);
