// Generated by CoffeeScript 1.7.1

/*
  Load source modal dialog
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  levelEditor.view.ModalLoadSource = (function(_super) {
    __extends(ModalLoadSource, _super);

    ModalLoadSource.VID = "view-leditor-modal-load-source";

    ModalLoadSource.prototype.DT = "levelEditor.view.ModalLoadSource";

    function ModalLoadSource(el, app) {
      this.el = el;
      this.app = app;
      this.loadBtnClick = __bind(this.loadBtnClick, this);
      ModalLoadSource.__super__.constructor.apply(this, arguments);
      console.log(this.DT, "Init.");
      this.loadbtn = this.el.find("[load]");
      this.loadbtn.on("click", this.loadBtnClick);
    }

    ModalLoadSource.prototype.loadBtnClick = function() {
      return this.el.modal('hide');
    };

    return ModalLoadSource;

  })(levelEditor.Object);

}).call(this);
