// Generated by CoffeeScript 1.7.1

/*
  Load source modal dialog
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  levelEditor.view.ModalLoadSource = (function(_super) {
    __extends(ModalLoadSource, _super);

    ModalLoadSource.VID = "view-leditor-modal-load-source";

    ModalLoadSource.prototype.DT = "levelEditor.view.ModalLoadSource";

    function ModalLoadSource(el, app) {
      this.el = el;
      this.app = app;
      this.clearForm = __bind(this.clearForm, this);
      this.loadLevel = __bind(this.loadLevel, this);
      this.loadBtnClick = __bind(this.loadBtnClick, this);
      ModalLoadSource.__super__.constructor.apply(this, arguments);
      console.log(this.DT, "Init.");
      this.loadbtn = this.el.find("[load]");
      this.textarea = this.el.find("textarea[name=level-source]");
      this.loadbtn.on("click", this.loadBtnClick);
      this.el.on("hidden.bs.modal", this.clearForm);
    }

    ModalLoadSource.prototype.loadBtnClick = function() {
      this.loadLevel();
      return this.el.modal('hide');
    };

    ModalLoadSource.prototype.loadLevel = function() {
      var extraData, h, lc, level, lobject;
      lobject = this.textarea.val();
      if (lobject.length > 0) {
        h = utils.serializers.Level;
        level = h.parseSerializedFromString(lobject);
        lc = this.app.data.get("level-cells");
        extraData = {};
        extraData[lc.FLAG_LEVEL_LOADED] = true;
        return lc.set("levelCells", level, extraData);
      }
    };

    ModalLoadSource.prototype.clearForm = function() {
      return this.textarea.val("");
    };

    return ModalLoadSource;

  })(levelEditor.Object);

}).call(this);
