// Generated by CoffeeScript 1.7.1

/*
  Actor direction view
 */

(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  levelEditor.view.ActorDirection = (function(_super) {
    __extends(ActorDirection, _super);

    ActorDirection.prototype.DT = "levelEditor.view.ActorDirection";

    ActorDirection.VID = "view-leditor-actor-direction";

    function ActorDirection(view, app) {
      this.view = view;
      this.app = app;
      ActorDirection.__super__.constructor.apply(this, arguments);
      console.log(this.DT, "Init.");
    }

    return ActorDirection;

  })(levelEditor.Object);

}).call(this);
