// Generated by CoffeeScript 1.7.1

/*
  View source modal
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  levelEditor.view.ModalSource = (function(_super) {
    __extends(ModalSource, _super);

    ModalSource.VID = "view-leditor-modal-source";

    ModalSource.prototype.DT = "levelEditor.view.ModalSource";

    function ModalSource(el, app) {
      this.el = el;
      this.app = app;
      this.drawLevelSource = __bind(this.drawLevelSource, this);
      ModalSource.__super__.constructor.apply(this, arguments);
      console.log(this.DT, "Init.");
      this.textarea = this.el.find("[name='level-source']");
      this.el.on("show.bs.modal", this.drawLevelSource);
    }

    ModalSource.prototype.drawLevelSource = function() {
      return this.textarea.text(utils.serializers.Level.serializeToString(this.app.data.get("level-cells")));
    };

    return ModalSource;

  })(levelEditor.Object);

}).call(this);
