// Generated by CoffeeScript 1.7.1

/*
  Player entity
 */

(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  game.entities.Player = (function(_super) {
    __extends(Player, _super);

    Player.prototype.DT = "game.entities.Player";

    function Player(app) {
      this.app = app;
      Player.__super__.constructor.apply(this, arguments);
      console.log(this.DT, "Init.");
    }

    return Player;

  })(game.Object);

}).call(this);
