// Generated by CoffeeScript 1.7.1

/*
  Main file with namespace and imports
 */

(function() {
  if (window.chms == null) {
    window.chms = {};
  }

  if (window.chms.utils === void 0) {
    window.chms.utils = {};
  }

}).call(this);


// Generated by CoffeeScript 1.7.1

/*
 Generates a uniq number.
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  chms.utils.Uniq = (function() {
    function Uniq() {
      this.gen = __bind(this.gen, this);
      if (chms.utils.Uniq.__instance == null) {
        chms.utils.Uniq.__instance = this;
        this.flows = {
          "default": 0
        };
      } else {
        return chms.utils.Uniq.__instance;
      }
    }

    Uniq.prototype.gen = function(flow) {
      if (flow == null) {
        flow = "default";
      }
      if (this.flows[flow] == null) {
        this.flows[flow] = 0;
      }
      this.flows[flow]++;
      return this.flows[flow];
    };

    Uniq.gen = function(flow) {
      return new chms.utils.Uniq().gen(flow);
    };

    return Uniq;

  })();

}).call(this);

