// Generated by CoffeeScript 1.7.1

/*
  Actor class
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  window.Actor = (function() {
    function Actor() {
      this.reactActionCompleted = __bind(this.reactActionCompleted, this);
      this.place = __bind(this.place, this);
      this.move = __bind(this.move, this);
      this.noop = __bind(this.noop, this);
      this.act = __bind(this.act, this);
    }

    Actor.prototype.I_ACTION_COMPLETED = "action_completed";

    Actor.prototype.I_MOVED = "moved";

    Actor.prototype.act = function() {
      return this.noop();
    };

    Actor.prototype.noop = function() {
      return this.reactActionCompleted();
    };

    Actor.prototype.move = function() {
      return this.reactActionCompleted();
    };

    Actor.prototype.place = function(world, x, y, d) {
      return world.addEntity(this);
    };

    Actor.prototype.reactActionCompleted = function() {
      return $(this).trigger(this.I_ACTION_COMPLETED);
    };

    return Actor;

  })();

}).call(this);
