// Generated by CoffeeScript 1.7.1

/*
  Dummy actor attacks player when player in nearest cell
  Most of the times do nothing
 */

(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.DummyActor = (function(_super) {
    __extends(DummyActor, _super);

    function DummyActor() {
      return DummyActor.__super__.constructor.apply(this, arguments);
    }

    return DummyActor;

  })(Actor);

}).call(this);
