// Generated by CoffeeScript 1.7.1

/*
  Player actor
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  window.Player = (function(_super) {
    __extends(Player, _super);

    function Player() {
      this.act = __bind(this.act, this);
      return Player.__super__.constructor.apply(this, arguments);
    }

    Player.prototype.act = function() {
      return setTimeout(this.reactActionCompleted, 5000);
    };

    return Player;

  })(Actor);

}).call(this);
