// Generated by CoffeeScript 1.7.1

/*
  Namespaces
 */

(function() {
  if (window.chms == null) {
    window.chms = {};
  }

  if (window.chms.ard == null) {
    window.chms.ard = {};
  }

}).call(this);
// Generated by CoffeeScript 1.7.1

/*
  Abstract object - parent of all objects
 */

(function() {
  chms.ard.AbstractObject = (function() {
    function AbstractObject() {
      this.s = this.constructor;
    }

    return AbstractObject;

  })();

}).call(this);
// Generated by CoffeeScript 1.7.1

/*
  Array data type
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  chms.ard.ARDArray = (function(_super) {
    __extends(ARDArray, _super);

    ARDArray.I_DATA_INSERTED = "chms-ard-ARDArray:DataInserted";

    ARDArray.I_DATA_DELETED = "chms-ard-ARDArray:DataDeleted";

    ARDArray.I_DATA_CONCATED = "chms-ard-ARDArray:DataConcated";

    ARDArray.ERROR_NOT_AN_ARRAY = new Error("Not an array!");

    ARDArray.ERROR_INDEX_OUT_OF_BOUNDS = new Error("Index out of bounds!");

    function ARDArray(ard) {
      this.ard = ard;
      this.isArray = __bind(this.isArray, this);
      this.checkOutOfBounds = __bind(this.checkOutOfBounds, this);
      this.checkArray = __bind(this.checkArray, this);
      this.concat = __bind(this.concat, this);
      this.push = __bind(this.push, this);
      this["delete"] = __bind(this["delete"], this);
      this.insert = __bind(this.insert, this);
      ARDArray.__super__.constructor.apply(this, arguments);
    }

    ARDArray.prototype.insert = function(key, index, val, extraData) {
      var cv, setter;
      if (extraData == null) {
        extraData = {};
      }
      this.checkArray(key);
      this.checkOutOfBounds(key, index);
      cv = this.ard.get(key);
      cv = cv.slice(0, index).concat(val).concat(cv.slice(index));
      setter = (function(_this) {
        return function() {
          _this.ard._data[key] = cv;
          return _this.ard.sendImpuls(_this.s.I_DATA_INSERTED, key, {
            value: cv,
            inserted: val,
            index: index,
            extraData: extraData
          });
        };
      })(this);
      return this.ard.change(key, setter, cv, extraData);
    };

    ARDArray.prototype["delete"] = function(key, index, extraData) {
      var cv, dl, setter;
      if (extraData == null) {
        extraData = {};
      }
      this.checkArray(key);
      this.checkOutOfBounds(key, index);
      cv = this.ard.get(key);
      dl = cv[index];
      cv = cv.filter((function(_this) {
        return function(e, i) {
          return i !== index;
        };
      })(this));
      setter = (function(_this) {
        return function() {
          _this.ard._data[key] = cv;
          return _this.ard.sendImpuls(_this.s.I_DATA_DELETED, key, {
            value: cv,
            index: index,
            deleted: dl,
            extraData: extraData
          });
        };
      })(this);
      return this.ard.change(key, setter, cv, extraData);
    };

    ARDArray.prototype.push = function(key, val, extraData) {
      var setter;
      if (extraData == null) {
        extraData = {};
      }
      this.checkArray(key);
      setter = (function(_this) {
        return function() {
          var nv;
          _this.ard._data[key].push(val);
          nv = _this.ard._data[key];
          return _this.ard.sendImpuls(_this.s.I_DATA_INSERTED, key, {
            value: nv,
            index: nv.length - 1,
            inserted: val,
            extraData: extraData
          });
        };
      })(this);
      return this.ard.change(key, setter);
    };

    ARDArray.prototype.concat = function(key, val, extraData) {
      var setter;
      if (extraData == null) {
        extraData = {};
      }
      this.checkArray(key);
      setter = (function(_this) {
        return function() {
          _this.ard._data[key] = _this.ard._data[key].concat(val);
          return _this.ard.sendImpuls(_this.s.I_DATA_CONCATED, key, {
            concated: val,
            extraData: extraData
          });
        };
      })(this);
      return this.ard.change(key, setter, this.ard.get(key), extraData);
    };

    ARDArray.prototype.checkArray = function(key) {
      if (!this.isArray(key)) {
        throw this.s.ERROR_NOT_AN_ARRAY;
      }
    };

    ARDArray.prototype.checkOutOfBounds = function(key, index) {
      if (index < 0 || (index >= this.ard.get(key).length)) {
        throw this.s.ERROR_INDEX_OUT_OF_BOUNDS;
      }
    };

    ARDArray.prototype.isArray = function(key) {
      return $.isArray(this.ard.get(key));
    };

    return ARDArray;

  })(chms.ard.AbstractObject);

}).call(this);
// Generated by CoffeeScript 1.7.1

/*
  Object data type
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  chms.ard.ARDObject = (function(_super) {
    __extends(ARDObject, _super);

    ARDObject.prototype.DT = "chms.ard.ARDObject";

    ARDObject.ERROR_NOT_AN_OBJECT = new Error("Not an object!");

    ARDObject.ERROR_NESTED_NOT_AN_OBJECT = new Error("Nested key not an object!");

    ARDObject.I_DATA_DELETED = "chms-ard-ARDObject:DataDeleted";

    function ARDObject(ard) {
      this.ard = ard;
      this.getKeysFromPath = __bind(this.getKeysFromPath, this);
      this.checkObject = __bind(this.checkObject, this);
      this["delete"] = __bind(this["delete"], this);
      this.get = __bind(this.get, this);
      this.set = __bind(this.set, this);
      ARDObject.__super__.constructor.apply(this, arguments);
    }

    ARDObject.prototype.set = function(key, path, val, extraData) {
      var keys, setter;
      if (extraData == null) {
        extraData = {};
      }
      this.checkObject(key);
      keys = this.getKeysFromPath(path);
      setter = (function(_this) {
        return function() {
          var ckey, croot, i, _i, _len;
          croot = _this.ard.get(key);
          for (i = _i = 0, _len = keys.length; _i < _len; i = ++_i) {
            ckey = keys[i];
            if ((i + 1) === keys.length) {
              croot[ckey] = val;
              return;
            }
            if (croot[ckey] == null) {
              croot[ckey] = {};
            }
            if (!_this.isObject(croot[ckey])) {
              throw _this.s.ERROR_NESTED_NOT_AN_OBJECT;
            }
            croot = croot[ckey];
          }
        };
      })(this);
      return this.ard.change(key, setter, void 0, $.extend(extraData, {
        path: path,
        parsedPath: keys
      }));
    };

    ARDObject.prototype.get = function(key, path) {
      var ckey, croot, cvalue, i, keys, _i, _len;
      this.checkObject(key);
      keys = this.getKeysFromPath(path);
      croot = this.ard.get(key);
      for (i = _i = 0, _len = keys.length; _i < _len; i = ++_i) {
        ckey = keys[i];
        cvalue = croot[ckey];
        if ((i + 1) === keys.length) {
          return cvalue;
        } else if ((cvalue != null) && this.isObject(cvalue)) {
          croot = cvalue;
        } else {
          return void 0;
        }
      }
    };

    ARDObject.prototype["delete"] = function(key, path, extraData) {
      var keys, setter;
      if (extraData == null) {
        extraData = {};
      }
      this.checkObject(key);
      keys = this.getKeysFromPath(path);
      setter = (function(_this) {
        return function() {
          var ckey, croot, cvalue, i, _i, _len;
          croot = _this.ard.get(key);
          for (i = _i = 0, _len = keys.length; _i < _len; i = ++_i) {
            ckey = keys[i];
            cvalue = croot[ckey];
            if ((i + 1) === keys.length) {
              delete croot[ckey];
              _this.ard.sendImpuls(_this.s.I_DATA_DELETED, key, {
                deleted: cvalue,
                path: path,
                parsedPath: keys,
                extraData: extraData
              });
              return true;
            } else if (typeof cvalue !== void 0) {
              croot = cvalue;
            } else {
              return false;
            }
          }
        };
      })(this);
      return this.ard.change(key, setter, void 0, $.extend(extraData, {
        path: path,
        parsedPath: keys
      }));
    };

    ARDObject.prototype.checkObject = function(key) {
      if (!this.isObject(this.ard.get(key))) {
        throw this.s.ERROR_NOT_AN_OBJECT;
      }
    };

    ARDObject.prototype.isObject = function(obj) {
      var type;
      type = typeof obj;
      return type === 'function' || type === 'object' && !!obj;
    };

    ARDObject.prototype.getKeysFromPath = function(path) {
      return path.split(".");
    };

    return ARDObject;

  })(chms.ard.AbstractObject);

}).call(this);
// Generated by CoffeeScript 1.7.1

/*
  Abstract reactive data main class
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; };

  chms.ard.AbstractReactiveData = (function() {
    AbstractReactiveData.I_BEFORE_DATA_CHANGE = "impuls.BeforeDataChange";

    AbstractReactiveData.I_DATA_CHANGED = "impuls.DataChanged";

    AbstractReactiveData.I_BASE = "impuls.Base";

    AbstractReactiveData.I_NOTIFICATION = "impuls.Notification";

    AbstractReactiveData.I_DATA_ADDED = "impuls.DataAdded";

    function AbstractReactiveData() {
      this.sendImpuls = __bind(this.sendImpuls, this);
      this.notify = __bind(this.notify, this);
      this.get = __bind(this.get, this);
      this.change = __bind(this.change, this);
      this.setIfUnequal = __bind(this.setIfUnequal, this);
      this.set = __bind(this.set, this);
      this.initDataTypes = __bind(this.initDataTypes, this);
      this.init = __bind(this.init, this);
      this.s = this.constructor;
      this.init();
      this.initDataTypes();
    }

    AbstractReactiveData.prototype.init = function() {
      return this._data = {};
    };

    AbstractReactiveData.prototype.initDataTypes = function() {
      this.tarray = new chms.ard.ARDArray(this);
      return this.tobject = new chms.ard.ARDObject(this);
    };

    AbstractReactiveData.prototype.set = function(key, val, extraData) {
      if (extraData == null) {
        extraData = {};
      }
      this.change(key, ((function(_this) {
        return function() {
          return _this._data[key] = val;
        };
      })(this)), val, extraData);
      return true;
    };

    AbstractReactiveData.prototype.setIfUnequal = function(key, val, extraData) {
      var cv;
      if (extraData == null) {
        extraData = {};
      }
      cv = this.get(key);
      if (cv !== val) {
        return this.set(key, val, extraData);
      } else {
        return false;
      }
    };

    AbstractReactiveData.prototype.change = function(key, setter, next, extraData) {
      var bd, pv;
      if (extraData == null) {
        extraData = {};
      }
      pv = this.get(key);
      bd = {
        value: pv
      };
      if (next != null) {
        bd.next = next;
      }
      bd.extraData = extraData;
      this.sendImpuls(this.s.I_BEFORE_DATA_CHANGE, key, bd);
      setter(key);
      return this.sendImpuls(this.s.I_DATA_CHANGED, key, {
        prevValue: pv,
        extraData: extraData
      });
    };

    AbstractReactiveData.prototype.get = function(key) {
      return this._data[key];
    };

    AbstractReactiveData.prototype.notify = function(key) {
      return this.sendImpuls(this.s.I_NOTIFICATION, key);
    };

    AbstractReactiveData.prototype.sendImpuls = function(type, key, additionalData) {
      var data;
      if (additionalData == null) {
        additionalData = {};
      }
      if (type !== this.s.I_BASE) {
        this.sendImpuls(this.s.I_BASE, key, {
          actualImpuls: type
        });
      }
      data = {
        type: type,
        key: key,
        value: this.get(key)
      };
      data = $.extend(data, additionalData);
      return $(this).trigger(data);
    };

    return AbstractReactiveData;

  })();

}).call(this);