// Generated by CoffeeScript 1.7.1

/*
  Model for player actor
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  models.actors.Player = (function(_super) {
    __extends(Player, _super);

    function Player() {
      this.initAnimationsDictionary = __bind(this.initAnimationsDictionary, this);
      return Player.__super__.constructor.apply(this, arguments);
    }

    Player.prototype.DT = "models.actors.Player";

    Player.prototype.initAnimationsDictionary = function() {
      return this._animations = {
        move: {
          cl: "",
          time: 500
        }
      };
    };

    return Player;

  })(models.actors.Empty);

}).call(this);
