// Generated by CoffeeScript 1.7.1

/*
  Empty actor model
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  models.actors.Empty = (function(_super) {
    __extends(Empty, _super);

    function Empty() {
      this.getTemplate = __bind(this.getTemplate, this);
      return Empty.__super__.constructor.apply(this, arguments);
    }

    Empty.prototype.DT = "models.actors.Empty";

    Empty.prototype.getTemplate = function() {
      return "<div class=\"model-empty\" style=\"display: none\"></div>";
    };

    return Empty;

  })(models.actors.Abstract);

}).call(this);
