// Generated by CoffeeScript 1.7.1

/*
  Abstract model
 */

(function() {
  models.Abstract = (function() {
    function Abstract() {
      this.s = this.constructor;
    }

    return Abstract;

  })();

}).call(this);
