// Generated by CoffeeScript 1.7.1

/*
  Abstract actor
 */

(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gameLogic.actors.AbstractActor = (function(_super) {
    __extends(AbstractActor, _super);

    AbstractActor.UID_KEY = "actor";

    function AbstractActor() {
      AbstractActor.__super__.constructor.apply(this, arguments);
      this.id = chms.utils.Uniq.gen(this.s.UID_KEY);
    }

    return AbstractActor;

  })(gameLogic.Object);

}).call(this);
