// Generated by CoffeeScript 1.7.1

/*
  Abstract character
 */

(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gameLogic.characters.AbstractCharacter = (function(_super) {
    __extends(AbstractCharacter, _super);

    AbstractCharacter.UID_KEY = "character";

    function AbstractCharacter() {
      AbstractCharacter.__super__.constructor.apply(this, arguments);
      this.uid = chms.utils.Uniq.gen(this.s.UID_KEY);
    }

    return AbstractCharacter;

  })(gameLogic.Object);

}).call(this);
