// Generated by CoffeeScript 1.7.1

/*
  Player entity
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gameLogic.actors.Player = (function(_super) {
    __extends(Player, _super);

    function Player() {
      this.initState = __bind(this.initState, this);
      return Player.__super__.constructor.apply(this, arguments);
    }

    Player.prototype.DT = "gameLogic.actors.Player";

    Player.prototype.initState = function() {
      this.set("maxHealth", 200);
      return this.set("currentHealth", 200);
    };

    return Player;

  })(gameLogic.actors.AbstractActor);

}).call(this);
