// Generated by CoffeeScript 1.7.1

/*
  Game app
 */

(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gameLogic.App = (function(_super) {
    __extends(App, _super);

    App.prototype.DT = "gameLogic.App";

    function App() {
      App.__super__.constructor.apply(this, arguments);
      this.world = new gameLogic.entities.World(this);
      this.time = new gameLogic.entities.Time(this);
      this.player = new gameLogic.actors.Player(this);
    }

    return App;

  })(gameLogic.Object);

}).call(this);
