// Generated by CoffeeScript 1.7.1

/*
  Time data
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gameLogic.data.Time = (function(_super) {
    __extends(Time, _super);

    Time.prototype.DT = "gameLogic.data.Time";

    function Time() {
      this.init = __bind(this.init, this);
      Time.__super__.constructor.apply(this, arguments);
      console.log(this.DT, "Init.");
    }

    Time.prototype.init = function() {
      Time.__super__.init.apply(this, arguments);
      this.set("state", null);
      return this.set("roundNumber", 0);
    };

    return Time;

  })(chms.ard.AbstractReactiveData);

}).call(this);
