// Generated by CoffeeScript 1.7.1

/*
  World data
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gameLogic.data.World = (function(_super) {
    __extends(World, _super);

    World.prototype.DT = "gameLogic.data.World";

    function World() {
      this.init = __bind(this.init, this);
      World.__super__.constructor.apply(this, arguments);
      console.log(this.DT, "Init.");
    }

    World.prototype.init = function() {
      World.__super__.init.apply(this, arguments);
      this.set("level", null);
      return this.set("entities", null);
    };

    return World;

  })(chms.ard.AbstractReactiveData);

}).call(this);
