// Generated by CoffeeScript 1.7.1

/*
  Dummy actor attacks player when player in nearest cell
  Most of the times do nothing
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gameLogic.actors.DummyActor = (function(_super) {
    __extends(DummyActor, _super);

    function DummyActor() {
      this.act = __bind(this.act, this);
      this.initState = __bind(this.initState, this);
      return DummyActor.__super__.constructor.apply(this, arguments);
    }

    DummyActor.prototype.initState = function() {
      this.data.set("maxHealth", 50);
      return this.data.set("currentHealth", 50);
    };

    DummyActor.prototype.act = function() {
      return this.actionNoop();
    };

    return DummyActor;

  })(gameLogic.actors.AbstractActor);

}).call(this);
