// Generated by CoffeeScript 1.7.1

/*
  Round system
 */

(function() {
  var __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gameLogic.entities.Time = (function(_super) {
    __extends(Time, _super);

    Time.prototype.DT = "gameLogic.entities.Time";

    function Time(app) {
      this.app = app;
      this.create = __bind(this.create, this);
      this.stateTurn = __bind(this.stateTurn, this);
      this.stateUpdated = __bind(this.stateUpdated, this);
      Time.__super__.constructor.apply(this, arguments);
      console.log(this.DT, "Init.");
      this.data = new gameLogic.data.Time();
      $(this.data).asEventStream(this.data.s.I_DATA_CHANGED).filter((function(_this) {
        return function(v) {
          return v.key === "state";
        };
      })(this)).onValue(this.stateUpdated);
    }

    Time.TURN_TIME = 5000;

    Time.TURN_AFTERTIME = 300;

    Time.prototype.stateUpdated = function() {
      switch (this.data.get("state")) {
        case this.data.s.ROUND_STATE_START:
          this.data.set("state", this.data.s.ROUND_STATE_TURN);
          return this.stateUpdated();
        case this.data.s.ROUND_STATE_TURN:
          this.data.set("actorsMoveQueue", this.app.world.getActors());
          return this.stateTurn();
        case this.data.s.ROUND_STATE_END:
          this.data.set("state", this.data.s.ROUND_STATE_START);
          return this.stateUpdated();
      }
    };

    Time.prototype.stateTurn = function() {
      var actors, completed, p, turnTimeout;
      actors = this.data.get("actorsMoveQueue");
      if (actors.length === 0) {
        return setTimeout(((function(_this) {
          return function() {
            return _this.data.set("state", _this.data.s.ROUND_STATE_END);
          };
        })(this)), this.TURN_AFTERTIME);
      } else {
        p = actors[0];
        completed = (function(_this) {
          return function() {
            p.turnEnded();
            clearTimeout(turnTimeout);
            _this.data.tarray["delete"]("actorsMoveQueue", 0);
            return _this.stateTurn();
          };
        })(this);
        turnTimeout = setTimeout(p.noop, this.s.TURN_TIME);
        $(p).one(p.I_ACTION_COMPLETED, completed);
        return p.turnStart();
      }
    };

    Time.prototype.create = function() {
      this.data.setInitialValues();
      return this.stateUpdated();
    };

    return Time;

  })(gameLogic.Object);

}).call(this);
