// Generated by CoffeeScript 1.7.1

/*
  Abstract game object
 */

(function() {
  gameLogic.Object = (function() {
    function Object() {
      this.s = this.constructor;
    }

    return Object;

  })();

}).call(this);
