// Generated by CoffeeScript 1.7.1

/*
  Abstract game object
 */

(function() {
  var __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  gameLogic.Object = (function(_super) {
    __extends(Object, _super);

    function Object() {
      Object.__super__.constructor.apply(this, arguments);
    }

    return Object;

  })(abstract.Object);

}).call(this);
