// Generated by CoffeeScript 1.7.1
(function() {
  var centerGrid, getCenterGridX, getCenterGridY, getIndex, getXYfromCell, makeCell, positionGrid, renderGrid;

  renderGrid = function(size) {
    var cols, container, i, ii, j, rows, startAt, xy;
    startAt = Date.now();
    rows = '';
    i = 0;
    while (i < size) {
      ii = i.toString();
      cols = '';
      j = 0;
      while (j < size) {
        xy = 'x=\'' + j + '\' y=\'' + ii + '\'';
        cols += '<div class=\'grid__col\' cell ' + xy + '></div>';
        j++;
      }
      rows += '<div class=\'grid__row\'>' + cols + '</div>';
      i++;
    }
    container = '<div class=\'grid\'>' + rows + '</div>';
    levelEditorEl.append(container);
    console.log('Ended by', Date.now() - startAt);
    return levelEditorEl.find('.grid');
  };

  getCenterGridX = function() {
    return -Math.round(grid.width() / 2);
  };

  getCenterGridY = function() {
    return -Math.round(grid.height() / 2);
  };

  positionGrid = function() {
    grid.css({
      top: gX,
      left: gY
    });
  };

  getXYfromCell = function(cell) {
    return {
      x: parseInt(cell.attr('x')),
      y: parseInt(cell.attr('y'))
    };
  };

  getIndex = function(x, y) {
    return x + 'x' + y;
  };

  makeCell = function() {
    return {
      n: 'face',
      s: 'face',
      w: 'face',
      e: 'face'
    };
  };

  centerGrid = function() {
    window.gX = getCenterGridX();
    window.gY = getCenterGridY();
    positionGrid();
  };

  window.drawLevel = function() {
    var cell, coords, index, _results;
    console.log("Draw level", window.level);
    levelEditorEl.find(".level-cell").removeClass("level-cell");
    _results = [];
    for (index in level) {
      cell = level[index];
      coords = index.split("x");
      _results.push(levelEditorEl.find("[x='" + coords[0] + "'][y='" + coords[1] + "']").addClass("level-cell"));
    }
    return _results;
  };

  $(function() {
    window.level = {};
    window.levelEditorEl = $('#level-editor');
    window.grid = renderGrid(100);
    centerGrid();
    grid.find('[cell]').on('click', function(e) {
      var ci, el, xy;
      el = $(e.target);
      console.log('Click on', el, e);
      xy = getXYfromCell(el);
      ci = getIndex(xy.x, xy.y);
      if (e.altKey) {
        el.removeClass('level-cell');
        delete level[ci];
      } else {
        el.addClass('level-cell');
        level[ci] = makeCell();
        level[ci].cell = el;
      }
    });
  });

}).call(this);
