// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    var area, modal;
    modal = $("#modalLoad");
    area = modal.find("[name='levelJson']");
    return modal.find("button[load-level]").click(function(e) {
      var level;
      level = area.val();
      if (level.length > 0) {
        window.level = JSON.parse(level);
        return window.drawLevel();
      }
    });
  });

}).call(this);
