// Generated by CoffeeScript 1.7.1
(function() {
  $(function() {
    return $('#modalSave').on('shown.bs.modal', function() {
      return $("#modalSave [name='levelJson']").text(JSON.stringify(window.level));
    });
  });

}).call(this);
